### ISSUE TITLE
License suite adoption guidelines

### ISSUE THREAD

**Issue by janetpkr** [creativecommons/platform-initiative#41]
@peterspdx @sarahpearson I would like to make the License Suite Adoption Guidelines from the platform plan public on the [wiki](https://github.com/creativecommons/platform-initiative/wiki) as I've made the other sections of the plan. Any objections?

**Comment by sarahpearson** [comment]
I don't see any reason not to make it public since they aren't framed as hard and fast rules. Ultimately, I think it would be great to mold our recommendations to platforms in a way that is more tied to a holistic look at the platform's business model though. Not sure what that looks like yet, but something to aim for eventually.

**Comment by janetpkr** [comment]
Yeah, that would be good, but would those be general guidelines or just highlighting the fact that each business model is different? I guess we'll find out!

@peterspdx This is assigned to you for final ok.

**Comment by peterspdx** [comment]
With the edits we've iterated, I'm good.
